#!/usr/bin/env python3
"""
Kraang CLI - Constraint Rationalization Engine
"""
import sys
import os

# Add src directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from kraang import main

if __name__ == '__main__':
    main()
